### PR TITLE
Feature Parity: Tier 1 priority fixes

### LINKED ISSUE #614: Feature Parity: Priority fixes before shared package extraction
## Feature Parity: Priority fixes before shared package extraction

This issue tracks the highest-priority bug fixes and feature gaps identified in `vscode-isort` as part of the cross-extension feature parity analysis.

These are **Tier 1 infrastructure issues** that affect 3-5 repos each and should be addressed before or during the extraction of shared code into `vscode-python-tool-lsp`. Fixing these in the shared package will resolve them across all extensions simultaneously.

See the full analysis: microsoft/vscode-python-tools-extension-template#290

### Fixes (5 items)

| Issue Description | Is Implemented | Fix Description | Repo Issue Tracking | Related Issues | Related PRs |
|-------------------|---------------|-----------------|--------------------:|----------------|-------------|
| When isort is sorting imports on a file, there is no visual progress or busy indicator in VS Code, leaving users unsure whether the extension is working or has stalled. | no | Required fix: This issue hasn't been reported yet in vscode-isort but exists in other extensions. Add a VS Code progress notification (e.g., using `window.withProgress`) while isort is actively processing a file. PR microsoft/vscode-pylint#687 can be used as a reference implementation. |  |  | microsoft/vscode-pylint#687 |
| The vscode-isort extension does not respect the `python.envFile` setting or `.env` files, so environment variables that affect import resolution (e.g., `PYTHONPATH`) are not loaded when isort runs. | no | Required fix: This issue hasn't been reported yet in vscode-isort but exists in other extensions. Read and apply environment variables from the configured `python.envFile` (or `.env` by default) before spawning the isort process. No reference PRs are available from other repos. |  |  |  |
| The vscode-isort extension does not support an `extraPaths` setting, so isort cannot resolve imports from additional source directories outside the workspace root (e.g., monorepo subdirectories or sha | no | Required fix: This issue hasn't been reported yet in vscode-isort but exists in other extensions. Add an `isort.extraPaths` setting that appends additional directories to the Python path when running isort. PR microsoft/vscode-pylint#524 can be used as a reference implementation. |  |  | microsoft/vscode-pylint#524 |
| The vscode-isort extension fails to process files or projects that use symbolic links, raising errors (e.g., ValueError) or silently skipping symlinked files and directories. | no | Required fix: This issue hasn't been reported yet in vscode-isort but exists in other extensions. Resolve symbolic links before passing file paths to isort, and ensure workspace path resolution handles symlinked directories correctly. PRs microsoft/vscode-black-formatter#460, microsoft/vscode-black- |  |  | microsoft/vscode-black-formatter#460, microsoft/vscode-black-formatter#4215, microsoft/vscode-mypy#396 |
| The vscode-isort extension makes file save operations very slow, with isort's on-save import sorting taking several seconds and blocking the save workflow. | no | Required fix: Investigate and optimize the on-save isort execution to reduce latency. Consider running isort asynchronously, caching results for unchanged files, or adding a timeout. PR microsoft/vscode-pylint#457 can be used as a reference implementation. | microsoft/vscode-isort#160, microsoft/vscode-isort#175 |  | microsoft/vscode-pylint#457 |

---
*Auto-generated from cross-extension feature parity analysis. See microsoft/vscode-python-tools-extension-template#290 for methodology and full results.*

### PR DESCRIPTION
**Pull request by edvilme**
Implements priority bug fixes identified in cross-extension feature parity analysis.

### 1. envFile/.env support
Read and apply environment variables from the configured \python.envFile\ setting (defaults to \.env\) before spawning the isort process. This ensures environment variables like \PYTHONPATH\ are available to isort.

### 2. extraPaths setting
Add \isort.extraPaths\ setting that appends additional directories to the Python path when running isort. Falls back to \python.analysis.extraPaths\ if not set. Also adds tilde (\~\) expansion support in path settings.

### 3. Symlink handling
Resolve symbolic links before comparing file paths, preventing silent failures when files or workspace directories are accessed through symlinks.

### 4. Save performance
Enable cancellation token support in script runner with a 30-second timeout to prevent hanging processes. Add content-based caching to skip redundant diagnostic runs when file content hasn't changed.

Fixes #614
Ref microsoft/vscode-python-tools-extension-template#290

### CODE REVIEW

File: src/common/server.ts [hunk 1]
```diff
@@ -27,11 +28,18 @@ async function createServer(
     initializationOptions: IInitOptions,
 ): Promise<LanguageClient> {
     const command = settings.interpreter[0];
-    const workspaceUri = Uri.parse(settings.workspace);
+    const workspaceUri = Uri.file(settings.workspace);
```
Comment (rchiodo) [inline src/common/server.ts]: Copilot generated:
**Regression**: `Uri.file(settings.workspace)` is incorrect. `settings.workspace` stores `workspace.uri.toString()` — a URI string like `file:///path/to/workspace`, not a filesystem path. `Uri.file()` treats its argument as a raw path, producing a double-encoded URI (e.g., `file:///file%3A%2F%2F%2Fpath...`). This breaks `cwd` resolution for the server process, especially on Windows. Revert to `Uri.parse(settings.workspace)`, which was correct.

File: src/common/server.ts [hunk 2]
```diff
@@ -27,11 +28,18 @@ async function createServer(
...
     const cwd = settings.cwd === '${fileDirname}' ? workspaceUri.fsPath : settings.cwd;
 
-    // Set debugger path needed for debugging python code.
+    // Load environment variables from .env file (python.envFile setting)
+    const projectRoot = await getProjectRoot();
```
Comment (rchiodo) [inline src/common/server.ts]: Copilot generated:
-40

**Unresolved prior issue (High)**: `getProjectRoot()` returns the first/active workspace folder, not the workspace associated with the document being processed. In multi-root workspaces, this loads the wrong `.env` file. The correct workspace is already available — `settings.workspace` is passed into `createServer`. Convert it to a `WorkspaceFolder` and pass it to `getEnvFileVars()` instead of using `getProjectRoot()`. This same env-loading block is duplicated in `runner.ts` (lines 143-148) — consider extracting a shared `buildProcessEnv(workspaceFolder)` helper to eliminate both the bug and the duplication.

File: src/common/runner.ts [hunk 3]
```diff
@@ -129,8 +142,13 @@ function getSeverity(sev: string): DiagnosticSeverity {
     return DiagnosticSeverity.Error;
 }
```
Comment (rchiodo) [inline src/common/runner.ts:180]: Copilot generated:
-148

**Unresolved prior issue (High)**: Same `getProjectRoot()` bug as `server.ts`. `getUpdatedEnvVariables` receives `settings` (which has `settings.workspace`), but ignores it and calls the global `getProjectRoot()`. Use the workspace from `settings` to load the correct `.env` file for the document being processed.

File: src/common/runner.ts [hunk 4]
```diff
@@ -71,8 +84,8 @@ export function runScript(
             scriptProc.stdin?.end(input, 'utf-8');
         }
         token?.onCancellationRequested(() => {
```
Comment (rchiodo) [inline src/common/runner.ts]: Copilot generated:
-89

**Unresolved prior issue (High)** + **new concern**: The cancellation handler resolves with `{ stdout: '', stderr: '' }`, making cancellation indistinguishable from a legitimate empty result. Combined with the new `timeout: SCRIPT_TIMEOUT_MS` at line 71, there are now two kill paths with confused semantics — timeout triggers a rejection via the `exec` callback, while cancellation triggers a resolution. Callers like `diagnosticRunner` will silently publish empty diagnostics on cancellation instead of preserving the previous state.

Suggested fix: Either reject with a `CancellationError`, or return a discriminated result (e.g., `{ stdout, stderr, cancelled: boolean }`) so callers can handle cancellation explicitly.

File: src/common/sortImports.ts [hunk 5]
```diff
@@ -140,17 +143,25 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
         workspace.onDidOpenTextDocument(async (td: TextDocument) => {
             if (td.languageId === 'python') {
                 const diagnostics = await diagnosticRunner(serverId, td);
                 diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                diagnosticContentCache.set(td.uri.toString(), td.getText());
             }
         }),
         workspace.onDidSaveTextDocument(async (td: TextDocument) => {
             if (td.languageId === 'python') {
+                const content = td.getText();
```
Comment (rchiodo) [inline src/common/sortImports.ts:177]: Copilot generated:
-164

**Unresolved prior issue (High)**: The cache is read before `await diagnosticRunner()` but written after. Two rapid saves both miss the cache and both run diagnostics, defeating the optimization. Move the cache write **before** the await:

```typescript
if (diagnosticContentCache.get(key) === content) {
    return;
}
diagnosticContentCache.set(key, content); // set before await
const diagnostics = await diagnosticRunner(serverId, td);
diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
```

This ensures the second save sees the cache entry immediately.

File: src/common/sortImports.ts [hunk 6]
```diff
@@ -36,6 +36,8 @@ function _isNotebookCell(uri: Uri): boolean {
 }
 
 let disposables: Disposable[] = [];
+const diagnosticContentCache = new Map<string, string>();
+
 export function unRegisterSortImportFeatures(): void {
```
Comment (rchiodo) [inline src/common/sortImports.ts:47]: Copilot generated:
**Unresolved prior issue (Medium)**: `diagnosticContentCache` stores full file text as values. While bounded by open document count (cleaned on close), replacing with a content hash (e.g., `crypto.createHash('sha256').update(content).digest('hex')`) would reduce per-entry memory from potentially hundreds of KB to 64 bytes, with no functional difference.

File: src/common/settings.ts [hunk 7]
```diff
@@ -49,6 +50,8 @@ function resolveVariables(
     const home = process.env.HOME || process.env.USERPROFILE;
     if (home) {
         substitutions.set('${userHome}', home);
+        substitutions.set('~/', `${home}/`);
```
Comment (rchiodo) [inline src/common/settings.ts]: Copilot generated:
-54

**Unresolved prior issue (Medium)**: Tilde expansion via `substitutions.set('~/', ...)` uses `String.replace()` which matches `~/` anywhere in the string, not just at the start. A path like `/data/~/config` would be incorrectly expanded. Replace with prefix-only logic:

```typescript
if (value.startsWith('~/')) value = home + value.slice(1);
else if (value.startsWith('~\\')) value = home + value.slice(1);
```

Low practical risk but easy to fix correctly.

File: bundled/tool/lsp_server.py [hunk 8]
```diff
@@ -667,6 +674,20 @@ def _get_settings_by_document(document: workspace.TextDocument | None):
 # *****************************************************
 # Internal execution APIs.
 # *****************************************************
+def _get_updated_env(settings: Dict[str, Any]) -> Dict[str, str]:
```
Comment (rchiodo) [inline bundled/tool/lsp_server.py:687]: Copilot generated:
-688

`_get_updated_env` returns a new dict with only `LS_IMPORT_STRATEGY` and `PYTHONPATH` — it does not include `os.environ`. If downstream `runner_utils` passes this as the `env=` parameter to `subprocess` (which replaces the entire environment), then `.env` file variables loaded by the TypeScript host won't reach the isort subprocess in bundled mode. Verify how `env` is consumed: if it replaces `os.environ`, this needs to be `{**os.environ, 'LS_IMPORT_STRATEGY': ..., 'PYTHONPATH': ...}`.

File: src/common/envFile.ts [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+ */
+export function parseEnvFile(content: string): Map<string, string> {
+    const env = new Map<string, string>();
+    for (const rawLine of content.split(/\r?\n/)) {
+        const line = rawLine.trim();
+        if (!line || line.startsWith('#')) {
+            continue;
+        }
+        const eqIndex = line.indexOf('=');
+        if (eqIndex < 0) {
```
Comment (rchiodo) [inline src/common/envFile.ts]: Copilot generated:
-23

`parseEnvFile` doesn't handle the common `export KEY=VALUE` syntax (used when `.env` files double as shell scripts). Lines like `export FOO=bar` produce key `export FOO` instead of `FOO`. Consider stripping an optional `export ` prefix before parsing the key.

File: src/common/envFile.ts [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+            continue;
```
Comment (rchiodo) [inline src/common/envFile.ts]: I'm wondering if there's an npm module for parsing .env files. There is in python.

File: src/common/runner.ts [hunk 11]
```diff
@@ -71,8 +85,8 @@ export function runScript(
             scriptProc.stdin?.end(input, 'utf-8');
```
Comment (rchiodo) [inline src/common/runner.ts:116]: Copilot generated:
**Double-reject race on Promise (High).** When `token` fires `onCancellationRequested`, `scriptProc.kill()` sends SIGTERM, which causes the `exec` callback to fire with an error — calling `reject(err)`. Then this handler *also* calls `reject(new Error('Script execution was cancelled'))`. Node ignores the second reject, but the error surfaced to the user is non-deterministic.

Suggested fix: add a `let settled = false` guard. Set it in the `exec` callback before calling `resolve`/`reject`, and check it here. Or: set a `cancelled` flag before `kill()` and suppress the SIGTERM error in the callback:
```ts
let cancelled = false;
token?.onCancellationRequested(() => {
    cancelled = true;
    scriptProc.kill();
});
// In exec callback:
if (err && !cancelled) reject(err);
else if (cancelled) reject(new Error('Script execution was cancelled'));
```

File: src/common/runner.ts [hunk 12]
```diff
@@ -22,19 +25,29 @@ import { getWorkspaceFolder } from './vscodeapi';
 /**
  * Returns the filesystem path for a document, handling notebook cell URIs.
  * For notebook cells, strips the scheme to file: and drops the fragment (cell id).
+ * Resolves symlinks so that paths passed to isort match real filesystem paths.
  */
 function getDocumentPath(uri: Uri): string {
```
Comment (rchiodo) [inline src/common/runner.ts]: Copilot generated:
**`fs.realpathSync` is synchronous blocking I/O (Medium).** This runs on every document operation (save, diagnostic, edit). On network filesystems, WSL interop, or UNC paths, `realpathSync` can be slow or throw. The `catch` fallback is correct, but consider using `fs.promises.realpath` (async) since callers are already async, or caching resolved paths per URI.

Also note: on Windows, `exec`'s `timeout` option (line 69) sends SIGTERM which is effectively a no-op — Windows uses `TerminateProcess` instead, which kills with no cleanup. This may produce confusing behavior when combined with the cancellation path.

File: src/common/settings.ts [hunk 13]
```diff
@@ -80,6 +81,11 @@ function resolveVariables(
         for (const [key, value] of substitutions) {
             s = s.replace(key, value);
         }
+        if (home && s.startsWith('~/')) {
```
Comment (rchiodo) [inline src/common/settings.ts]: Copilot generated:
**Tilde expansion blast radius (High).** This change is inside the generic `resolveVariables` function, which is called for `cwd`, `args`, `path`, `interpreter`, *and* `extraPaths`. Any user with a literal `~/` in their `args` or `path` settings (e.g., `--config ~/myconfig.cfg`) will now see it expanded where it previously was not. This is a silent behavioral change across all setting types.

Suggested fix: move tilde expansion into `getExtraPaths` specifically, or verify and document that tilde expansion is intentionally desired for all settings. Also, the two branches execute identical code and can be collapsed:
```ts
if (home && (s.startsWith('~/') || s.startsWith('~\\'))) {
    s = home + s.slice(1);
}
```

File: src/common/sortImports.ts [hunk 14]
```diff
@@ -140,17 +143,30 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
+            diagnosticContentCache.delete(td.uri.toString());
         }),
         workspace.onDidOpenTextDocument(async (td: TextDocument) => {
             if (td.languageId === 'python') {
                 const diagnostics = await diagnosticRunner(serverId, td);
                 diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                diagnosticContentCache.set(td.uri.toString(), td.getText());
             }
         }),
         workspace.onDidSaveTextDocument(async (td: TextDocument) => {
```
Comment (rchiodo) [inline src/common/sortImports.ts:175]: Copilot generated:
**Diagnostic cache race condition (High).** Setting the cache *before* `await diagnosticRunner()` prevents same-content duplicate runs but introduces a different race: if the diagnostic run fails, the `catch` block deletes the cache entry. A concurrent second save that arrived during the `await` would have seen the cache as matching and returned early — but now the first run failed (no diagnostics published) and the second run was skipped. Result: diagnostics silently disappear.

Suggested fix: only update the cache on success (move `diagnosticContentCache.set(key, content)` after `publishDiagnostics`). If duplicate-run prevention is important, use a pending-promise or generation-counter pattern instead of content-string equality.

File: src/common/sortImports.ts [hunk 15]
```diff
@@ -36,6 +36,8 @@ function _isNotebookCell(uri: Uri): boolean {
 }
 
 let disposables: Disposable[] = [];
+const diagnosticContentCache = new Map<string, string>();
```
Comment (rchiodo) [inline src/common/sortImports.ts:40]: Copilot generated:
**Unbounded content cache (Medium).** `diagnosticContentCache` stores full file content as `Map<string, string>`. Entries are only removed on `onDidCloseTextDocument`. In workspaces with many open Python files or large files, this silently increases memory usage. Consider using a content hash (e.g., simple FNV or SHA-256) instead of storing full text, which achieves the same deduplication with O(1) per-entry storage.

File: bundled/tool/lsp_server.py [hunk 16]
```diff
@@ -511,6 +508,15 @@ def initialize(params: lsp.InitializeParams) -> None:
         f"Global settings:\r\n{json.dumps(GLOBAL_SETTINGS, indent=4, ensure_ascii=False)}\r\n"
     )
 
+    # Add extra paths to sys.path
+    import_strategy = os.getenv("LS_IMPORT_STRATEGY", "useBundled")
+    setting = _get_settings_by_path(pathlib.Path(os.getcwd()))
```
Comment (rchiodo) [inline bundled/tool/lsp_server.py:520]: Copilot generated:
**`sys.path` grows monotonically on re-initialize (Medium).** `update_sys_path(extra, import_strategy)` appends to `sys.path` during `initialize`. If the client reconnects or settings change and `initialize` is called again, paths accumulate without deduplication or cleanup. This can cause stale module resolution.

Suggested fix: clear previously-added extra paths before re-adding, or deduplicate `sys.path` after the loop.

File: src/common/envFile.ts [hunk 17]
```diff
@@ -0,0 +1,41 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (rchiodo) [inline src/common/envFile.ts:1]: Copilot generated:
**No unit tests for `getEnvFileVars` (Medium).** This new module handles file I/O, `${workspaceFolder}` substitution, relative path resolution, and error recovery. It's called from two independent code paths (`server.ts` and `runner.ts`). At minimum, test: (1) successful parse, (2) missing file returns `{}`, (3) `${workspaceFolder}` substitution, (4) relative path resolution.

File: src/common/runner.ts (hunk 11 above)
Comment (edvilme) [reply src/common/runner.ts:116]: Fixed in 6251ad0

File: src/common/runner.ts (hunk 12 above)
Comment (edvilme) [reply src/common/runner.ts]: Fixed in 6b13450

File: src/common/settings.ts (hunk 13 above)
Comment (edvilme) [reply src/common/settings.ts]: Fixed in bc3484c

File: src/common/sortImports.ts (hunk 14 above)
Comment (edvilme) [reply src/common/sortImports.ts:175]: Fixed in 97cbdd7

File: src/common/sortImports.ts (hunk 15 above)
Comment (edvilme) [reply src/common/sortImports.ts:40]: Fixed in 3fd23e6

File: bundled/tool/lsp_server.py (hunk 16 above)
Comment (edvilme) [reply bundled/tool/lsp_server.py:520]: Fixed in 5353ac9

File: src/common/envFile.ts (hunk 17 above)
Comment (edvilme) [reply src/common/envFile.ts:1]: Fixed in db0406e

File: src/common/runner.ts [hunk 18]
```diff
@@ -49,30 +74,34 @@ export function runScript(
...
         const scriptProc = proc.execFile(
             runner,
             args,
             {
                 encoding: 'utf-8',
                 env: options?.newEnv,
                 cwd: options?.cwd,
+                timeout: SCRIPT_TIMEOUT_MS,
             },
             (err, stdout, stderr) => {
```
Comment (rchiodo) [inline src/common/runner.ts:96]: Copilot generated:
**Bug: Race condition between cancellation and successful completion.** If the `CancellationToken` fires just as the process exits successfully, `cancelled` is set to `true` before the `execFile` callback runs with `err = null`. The callback skips `err && !cancelled` (err is null), enters `else if (cancelled)`, and **rejects a perfectly valid result**. This causes intermittent lost formatting.

Fix: prioritize successful completion over the cancelled flag:
```typescript
if (options?.ignoreError || !err) {
    resolve({ stdout: stdout ?? '', stderr: stderr ?? '' });
} else if (cancelled) {
    reject(new Error('Script execution was cancelled'));
} else {
    reject(err);
}
```

File: src/common/runner.ts [hunk 19]
```diff
@@ -129,8 +158,16 @@ function getSeverity(sev: string): DiagnosticSeverity {
     return DiagnosticSeverity.Error;
 }
 
-function getUpdatedEnvVariables(settings: ISettings): { [x: string]: string | undefined } {
+async function getUpdatedEnvVariables(settings: ISettings): Promise<{ [x: string]: string | undefined }> {
```
Comment (rchiodo) [inline src/common/runner.ts:182]: Copilot generated:
**Duplicated env-building logic.** `getUpdatedEnvVariables` here and the nearly identical block in `server.ts:34-41` both call `getEnvFileVars()` and merge into `process.env`. Extract a shared `buildSubprocessEnv(settings, workspaceFolder)` helper to prevent these from diverging as features are added.

File: src/common/sortImports.ts [hunk 20]
```diff
@@ -140,17 +150,49 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
+                const key = td.uri.toString();
+                if (pendingRuns.has(key)) {
+                    return;
+                }
+                const content = td.getText();
+                const run = (async () => {
+                    try {
+                        const diagnostics = await diagnosticRunner(serverId, td);
+                        diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                        diagnosticContentCache.set(key, contentHash(content));
```
Comment (rchiodo) [inline src/common/sortImports.ts:166]: Copilot generated:
**Bug: Stale diagnostics cached after timeout/kill.** `diagnosticRunner` calls `runScript` with `ignoreError: true`, so a timed-out or killed process resolves with empty `stderr`. This produces `[]` diagnostics which get published (clearing real diagnostics), and then `diagnosticContentCache.set(key, contentHash(content))` caches the hash. On the next save with the same content, the cache hit causes an early return — diagnostics are permanently lost until the file is edited.

Fix: Only update the cache when the diagnostic run was not interrupted. One approach: have `diagnosticRunner` return a flag indicating whether the run completed normally, and only cache on success. Alternatively, don't cache when the result is empty and the process was killed.

File: src/common/sortImports.ts [hunk 21]
```diff
@@ -140,17 +150,49 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
+                    return;
+                }
+                if (pendingRuns.has(key)) {
+                    return;
+                }
+                const run = (async () => {
+                    try {
+                        const diagnostics = await diagnosticRunner(serverId, td);
+                        diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                        diagnosticContentCache.set(key, contentHash(content));
```
Comment (rchiodo) [inline src/common/sortImports.ts:192]: Copilot generated:
Same stale-cache bug exists in the `onDidSaveTextDocument` handler — `diagnosticContentCache.set(key, contentHash(content))` runs after a potentially interrupted diagnostic run. Both handlers (open and save) need the same fix.

File: src/common/settings.ts [hunk 22]
```diff
@@ -84,6 +85,14 @@ function resolveVariables(
     });
 }
 
+function expandTilde(value: string): string {
```
Comment (rchiodo) [inline src/common/settings.ts]: Copilot generated:
**`expandTilde` misses bare `~` and is applied inconsistently.** (1) A user setting `extraPaths: ["~"]` won't expand — the check requires `~/` or `~\`. Add a check for `value === '~'`. (2) Tilde expansion is applied to `cwd`, `path`, and `extraPaths` but not to `args` or `interpreter`. If intentional, document why; if not, apply uniformly to all path-type settings.

File: src/common/settings.ts [hunk 23]
```diff
@@ -122,6 +131,23 @@ function getCwd(config: WorkspaceConfiguration, workspace: WorkspaceFolder): str
     return resolveVariables([cwd], 'cwd', workspace)[0];
```
Comment (rchiodo) [inline src/common/settings.ts:136]: Copilot generated:
**No dedicated test for `expandTilde` or `getExtraPaths`.** Both are new utility functions with branching logic (tilde patterns, fallback to `python.analysis.extraPaths`). The existing settings test was updated to assert `extraPaths: []` but doesn't exercise the fallback path or tilde expansion. Consider adding targeted unit tests.

File: src/common/envFile.ts [hunk 24]
```diff
@@ -0,0 +1,41 @@
...
+
+/**
+ * Reads the env file configured via `python.envFile` (defaults to `${workspaceFolder}/.env`),
+ * parses it using dotenv, and returns the resulting environment variables.
+ * Returns an empty record if the file does not exist or cannot be read.
+ */
+export async function getEnvFileVars(workspace: WorkspaceFolder): Promise<Record<string, string>> {
+    const pythonConfig = getConfiguration('python', workspace.uri);
+    let envFilePath = pythonConfig.get<string>('envFile', '${workspaceFolder}/.env') ?? '${workspaceFolder}/.env';
+
```
Comment (rchiodo) [inline src/common/envFile.ts:20]: Copilot generated:
**envFile path not expanded with `~`.** `${workspaceFolder}` substitution is applied, but `expandTilde` is not called. A user with `"python.envFile": "~/.env"` gets the literal path `~/.env` which won't resolve. Apply `expandTilde` (or equivalent) after variable substitution.

File: src/common/server.ts [hunk 25]
```diff
@@ -30,8 +31,17 @@ async function createServer(
     const workspaceUri = Uri.parse(settings.workspace);
     const cwd = settings.cwd === '${fileDirname}' ? workspaceUri.fsPath : settings.cwd;
 
-    // Set debugger path needed for debugging python code.
+    // Load environment variables from .env file (python.envFile setting)
```
Comment (rchiodo) [inline src/common/server.ts:36]: Copilot generated:
**Inconsistent env file freshness.** `server.ts` loads `.env` once at server startup. `runner.ts` loads `.env` fresh on every diagnostic/format run. If the user edits `.env`, subprocess calls use updated values but the LSP server retains stale values until restart. Either both should cache (with invalidation on file change), or both should read fresh.

File: bundled/tool/lsp_server.py [hunk 26]
```diff
@@ -511,6 +511,23 @@ def initialize(params: lsp.InitializeParams) -> None:
...
+    # Add extra paths to sys.path (deduplicate on re-initialize)
+    global _extra_sys_paths
+    for p in _extra_sys_paths:
+        if p in sys.path:
+            sys.path.remove(p)
+    _extra_sys_paths.clear()
+
+    import_strategy = os.getenv("LS_IMPORT_STRATEGY", "useBundled")
+    setting = _get_settings_by_path(pathlib.Path(os.getcwd()))
+    for extra in setting.get("extraPaths", []):
```
Comment (rchiodo) [inline bundled/tool/lsp_server.py:521]: Copilot generated:
**`_extra_sys_paths` tracks paths that were never added to `sys.path`.** `update_sys_path` checks `os.path.isdir()` and silently skips non-existent directories, but `_extra_sys_paths.append(extra)` runs unconditionally. On re-initialize, phantom entries accumulate. Fix: only append after confirming the path was actually added:
```python
if extra not in sys.path:
    update_sys_path(extra, import_strategy)
    if extra in sys.path:  # verify it was actually added
        _extra_sys_paths.append(extra)
```

File: src/common/sortImports.ts [hunk 27]
```diff
@@ -140,17 +150,49 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
-                const diagnostics = await diagnosticRunner(serverId, td);
-                diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                const content = td.getText();
+                const key = td.uri.toString();
+                if (diagnosticContentCache.get(key) === contentHash(content)) {
+                    return;
+                }
+                if (pendingRuns.has(key)) {
+                    return;
+                }
```
Comment (rchiodo) [inline src/common/sortImports.ts:187]: Copilot generated:
**Concurrent saves silently dropped.** If a diagnostic run is in-flight (`pendingRuns.has(key)`), the second save returns immediately. If the second save introduced new import issues, they won't be detected until the *next* save. Consider queuing the re-run or cancelling the in-flight run. The Advocate acknowledges this is self-healing via the content hash on the following save, but the UX gap (missing diagnostics for one save cycle) may confuse users.

File: src/common/runner.ts [hunk 28]
```diff
@@ -11,30 +12,54 @@ import {
     Range,
     TextDocument,
     Uri,
+    workspace,
     WorkspaceEdit,
 } from 'vscode';
 import { RUNNER_SCRIPT_PATH } from './constants';
+import { getEnvFileVars } from './envFile';
 import { traceError, traceLog } from './logging';
```
Comment (rchiodo) [inline src/common/runner.ts:20]: Copilot generated:
**Unbounded `realpathCache` with no invalidation.** This `Map` grows with every unique file path and persists for the extension host lifetime. Symlink targets can change during development (e.g., `ln -sf`). Consider adding a max-size bound (e.g., LRU with 1000 entries) or at minimum documenting the no-invalidation trade-off.

File: src/common/runner.ts [hunk 29]
```diff
@@ -49,30 +74,34 @@ export function runScript(
...
             },
         );
         if (input) {
             scriptProc.stdin?.end(input, 'utf-8');
         }
         token?.onCancellationRequested(() => {
-            //resolve({ stdout: '', stderr: '' });
-            //scriptProc.kill();
+            cancelled = true;
+            scriptProc.kill();
```
Comment (rchiodo) [inline src/common/runner.ts]: Copilot generated:
**`scriptProc.kill()` may not terminate children on Windows.** `kill()` sends SIGTERM on Unix but may not reliably terminate child process trees on Windows. Consider using `tree-kill` or platform-specific termination if Windows support is important.

File: src/common/runner.ts [hunk 30]
```diff
@@ -49,30 +74,34 @@ export function runScript(
...
                 } else {
-                    resolve({ stdout, stderr });
+                    resolve({ stdout: stdout ?? '', stderr: stderr ?? '' });
                 }
             },
         );
         if (input) {
             scriptProc.stdin?.end(input, 'utf-8');
         }
         token?.onCancellationRequested(() => {
```
Comment (rchiodo) [inline src/common/runner.ts]: Copilot generated:
**`onCancellationRequested` disposable leaked.** The returned `Disposable` from `token?.onCancellationRequested(...)` is never stored or disposed. If the token outlives the process (e.g., a shared request-scoped token), handlers accumulate. Store the disposable and dispose it when the promise settles.

File: src/common/runner.ts (hunk 18 above)
Comment (edvilme) [reply src/common/runner.ts:96]: Fixed in e02293b

File: src/common/runner.ts (hunk 19 above)
Comment (edvilme) [reply src/common/runner.ts:182]: Fixed in e02293b

File: src/common/sortImports.ts (hunk 20 above)
Comment (edvilme) [reply src/common/sortImports.ts:166]: Fixed in cd05796

File: src/common/sortImports.ts (hunk 21 above)
Comment (edvilme) [reply src/common/sortImports.ts:192]: Fixed in cd05796

File: src/common/settings.ts (hunk 22 above)
Comment (edvilme) [reply src/common/settings.ts]: Fixed in 54f82f5

File: src/common/settings.ts (hunk 23 above)
Comment (edvilme) [reply src/common/settings.ts:136]: Fixed in 54f82f5

File: src/common/envFile.ts (hunk 24 above)
Comment (edvilme) [reply src/common/envFile.ts:20]: Fixed in 54f82f5

File: src/common/server.ts (hunk 25 above)
Comment (edvilme) [reply src/common/server.ts:36]: Fixed in cd05796

File: bundled/tool/lsp_server.py (hunk 26 above)
Comment (edvilme) [reply bundled/tool/lsp_server.py:521]: Fixed in f6b48f6

File: src/common/sortImports.ts (hunk 27 above)
Comment (edvilme) [reply src/common/sortImports.ts:187]: Fixed in cd05796

File: src/common/runner.ts (hunk 28 above)
Comment (edvilme) [reply src/common/runner.ts:20]: Fixed in 31dc25c

File: src/common/runner.ts (hunk 29 above)
Comment (edvilme) [reply src/common/runner.ts]: Fixed in e02293b

File: src/common/runner.ts (hunk 30 above)
Comment (edvilme) [reply src/common/runner.ts]: Fixed in e02293b

File: src/common/sortImports.ts [hunk 31]
```diff
@@ -140,17 +150,52 @@ export function registerSortImportFeatures(serverId: string): Disposable & { sta
...
             if (td.languageId === 'python') {
-                const diagnostics = await diagnosticRunner(serverId, td);
-                diagnosticsProvider.publishDiagnostics(td.uri, diagnostics);
+                const key = td.uri.toString();
+                if (pendingRuns.has(key)) {
+                    return;
+                }
+                const content = td.getText();
+                const run = (async () => {
+                    try {
```
Comment (rchiodo) [inline src/common/sortImports.ts:163]: Copilot generated:
-170

**Bug (High): Stale diagnostics cached after timeout.** `diagnosticRunner` calls `runScript` with `ignoreError: true`. When the 30s timeout fires, `execFile` kills the process and calls the callback with an error, but `ignoreError: true` causes it to resolve with empty `stdout`/`stderr`. `diagnosticRunner` returns `[]`, the `try` block succeeds, empty diagnostics are published (clearing real ones), and `diagnosticContentCache.set(key, contentHash(content))` caches the hash. On the next save with the same content, the cache hits and diagnostics are permanently lost.

The `catch` block never fires because `ignoreError: true` prevents rejection. The same issue exists in the `onDidSaveTextDocument` handler at line ~190.

**Suggested fix:** Have `runScript` return metadata about process termination (e.g., `{ stdout, stderr, killed: boolean }`) so callers can distinguish clean completions from killed processes. Then only cache when `!killed`. Alternatively, modify the `ignoreError` branch to reject when `err?.killed` is true:
```typescript
if (options?.ignoreError && !err?.killed) {
    resolve({ stdout, stderr });
} else if (err?.killed) {
    reject(new Error('Script timed out or was killed'));
}
```

Comment (edvilme) [reply src/common/sortImports.ts:163]: Fixed in 76ab391 — runScript now rejects when err.killed is true even with ignoreError, preventing stale empty diagnostics from being cached.

File: src/common/runner.ts [hunk 32]
```diff
@@ -129,8 +179,16 @@ function getSeverity(sev: string): DiagnosticSeverity {
     return DiagnosticSeverity.Error;
```
Comment (rchiodo) [inline src/common/runner.ts:179]: Copilot generated:
**Duplicated env-building logic (Medium).** The 6-line block here (`Uri.parse` → `getWorkspaceFolder` → `getEnvFileVars` → merge loop) is identical to `server.ts:31-41`. The comment in `server.ts` documents the intentional timing difference, but the code shape will diverge as features are added. Extract a shared `buildProcessEnv(workspaceFolder: WorkspaceFolder): Promise<Record<string, string>>` helper in `envFile.ts` to serve both call sites.

Comment (edvilme) [reply src/common/runner.ts:179]: Acknowledged. The duplication is intentional and documented in cd05796: server.ts loads env once at LSP startup for consistency, runner.ts loads fresh per script invocation. Extracting a shared helper would obscure this deliberate timing difference.

**Review by rchiodo — APPROVED** [review]
Approved via Review Center.
